trigger:
- main

variables:
  azureSubscription: '6aed446f-e263-43c5-8665-e02540be49df'
  webAppName: 'Javawebapp001'
  environmentName: 'Javawebapp001'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)  # Corrected: Only one vmImage
    steps:
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Keep only one TargetFolder

    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: drop

- stage: Deploy
  displayName: Deploy Linux Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)  # Corrected: Only one vmImage
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: Javawebapp001'
            inputs:
              azureSubscription: $(azureSubscription)  # Corrected: Only one azureSubscription
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Build.ArtifactStagingDirectory)/**/*.war'
